service:
    name: swamphacks-api

plugins:
    - serverless-webpack
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    logRetentionInDays: 1

custom:
    serverless-offline:
        httpPort: 1337

functions:
    login:
        handler: src/handlers/auth.login
        name: ${self:service}-${self:provider.stage}-login
        memorySize: 128
        events:
            - http:
                  method: post
                  path: login
    register:
        handler: src/handlers/auth.register
        name: ${self:service}-${self:provider.stage}-register
        memorySize: 128
        events:
            - http:
                  method: post
                  path: register
